
export const samplenewprods = [
    {
        "type": "normal",
        "groupId": 1,
        "categoryId": -1,
        "subCategoryId": -1,
        "brand": {
            "id": 1,
            "name": "Brand 1",
        },
        "products": [{
            "newProductMetaId": -1,
            "productInfo": {
                "productId": 4532,
                "barcode": "100000000000037",
                "productName": "Almond Non-Dairy Dessert Bar",
                "createdDate": "",
                "imageUrl": "https://d3ginyfiwc1r8i.cloudfront.net/main/14/100000000000037/HAFcaiC1eHY9zBgH9svjr_W100_100.png"
            },
            "strategy": {
                "option": "replace",
                "level": "brand",
                "productList": [],
                "minFaceLimit": 0,
            },
            "selectionOption": "none",
            "facing": {
                "method": "num",
                "value": 0
            },
            "testPeriod": 145,
            "isInOutProduct": false,
            "vmpVerList": []
        }],
    },
    {
        "type": "normal",
        "groupId": 2,
        "categoryId": -1,
        "subCategoryId": -1,
        "brand": {
            "id": 1,
            "name": "Brand 1",
        },
        "products": [{
            "newProductMetaId": -1,
            "productInfo": {
                "productId": 4532,
                "barcode": "100000000000013",
                "productName": "BARQS ROOT BEER 2L",
                "createdDate": "",
                "imageUrl": "https://d3ginyfiwc1r8i.cloudfront.net/main/14/100000000000013/k_PbQlIh69mTBwxxHPWAM_W100_100.png"
            },
            "strategy": {
                "option": "replace",
                "level": "brand",
                "productList": [],
                "minFaceLimit": 0,
            },
            "selectionOption": "none",
            "facing": {
                "method": "num",
                "value": 0
            },
            "testPeriod": 145,
            "isInOutProduct": false,
            "vmpVerList": []
        }],
    }
];

export const samplenotifications = [
    {
        "productImage": [],
        "isMvp": true,
        "isOnTop": false,
        "productTags": [],
        "departmentName": "SNACKS",
        "categoryName": "50g - 100g",
        "subCategoryName": "CHEESE - 50g - 100g",
        "isBrandSetFromGS1": false,
        "fromProductLookup": false,
        "snapId": -1,
        "isStackable": true,
        "maxStackableCount": 0,
        "mpId": null,
        "id": 4499,
        "width": 10,
        "height": 20,
        "uom": "cm",
        "depth": 8,
        "barcode": "100000000000004",
        "importBarcode": null,
        "productSource": "direct",
        "gs1Code": "",
        "posMappingId": null,
        "lastPriceOfProduct": null,
        "productName": "CHIPS AHOY! CHEWY CHEWY COOKIES 9.5 OZ",
        "isFavorite": false,
        "isNOOS": false,
        "isMandatory": false,
        "isPremium": false,
        "minQty": 0,
        "maxQty": 0,
        "minRevenue": 0,
        "maxRevenue": 0,
        "shelvesLife": 0,
        "paceOfSalesInQty": 0,
        "paceOfSalesInQtyUot": "per_day",
        "shelveLifeUot": "days",
        "revenueSource": null,
        "isManualAdded": true,
        "brandName": "Walker’s",
        "brandId": 50,
        "subCategoryId": 101,
        "subCategoryColor": "#e88c3c",
        "categoryColor": "#b320fc",
        "brandColor": "#00aec1",
        "supplierId": 27,
        "supplierName": "SNACKS & SOFT DRINKS SUP",
        "supplierColor": "#e08f16",
        "completeStatus": "FullData",
        "mpUsageStatus": "Old",
        "importName": null,
        "arigoName": null,
        "gs1Name": null,
        "importStatus": "None",
        "isBlock": false,
        "imageSource": "Custom",
        "hierarchyCompleteStatus": "Completed",
        "origin": "Other",
        "dimensionSource": "Other",
        "brandSource": "None",
        "imageId": 48764,
        "imageUrl": "https://d3ginyfiwc1r8i.cloudfront.net/main/14/100000000000004/sk_XBBmmnn90eaDJfzmqk_W100_100.png"
    },
    {
        "productImage": [],
        "isMvp": true,
        "isOnTop": false,
        "productTags": [],
        "departmentName": "SNACKS",
        "categoryName": "50g - 100g",
        "subCategoryName": "CHEESE - 50g - 100g",
        "isBrandSetFromGS1": false,
        "fromProductLookup": false,
        "snapId": -1,
        "isStackable": true,
        "maxStackableCount": 0,
        "mpId": null,
        "id": 4498,
        "width": 8,
        "height": 15,
        "uom": "cm",
        "depth": 8,
        "barcode": "100000000000003",
        "importBarcode": null,
        "productSource": "direct",
        "gs1Code": "",
        "posMappingId": null,
        "lastPriceOfProduct": null,
        "productName": "CHIPS AHOY! CHUNKY CHOCOLATE CHIP COOKIES, KING SIZE (4.15OZ)",
        "isFavorite": false,
        "isNOOS": false,
        "isMandatory": false,
        "isPremium": false,
        "minQty": 0,
        "maxQty": 0,
        "minRevenue": 0,
        "maxRevenue": 0,
        "shelvesLife": 0,
        "paceOfSalesInQty": 0,
        "paceOfSalesInQtyUot": "per_day",
        "shelveLifeUot": "days",
        "revenueSource": null,
        "isManualAdded": true,
        "brandName": "Walker’s",
        "brandId": 50,
        "subCategoryId": 101,
        "subCategoryColor": "#e88c3c",
        "categoryColor": "#b320fc",
        "brandColor": "#00aec1",
        "supplierId": 27,
        "supplierName": "SNACKS & SOFT DRINKS SUP",
        "supplierColor": "#e08f16",
        "completeStatus": "FullData",
        "mpUsageStatus": "Old",
        "importName": null,
        "arigoName": null,
        "gs1Name": null,
        "importStatus": "None",
        "isBlock": false,
        "imageSource": "Custom",
        "hierarchyCompleteStatus": "Completed",
        "origin": "Other",
        "dimensionSource": "Other",
        "brandSource": "None",
        "imageId": 48758,
        "imageUrl": "https://d3ginyfiwc1r8i.cloudfront.net/main/14/100000000000003/rwem-Au3KF3cdWIpu5NRD_W100_100.png"
    }
];